# -*- coding: utf-8 -*-
"""task 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tq9b40Af8cSd5JVYlVPpsMO-pJIMNQmH
"""

# Define two sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}

# Print the sets
print("Set 1:", set1)
print("Set 2:", set2)
print()

# Union of sets (elements in either set)
union_set = set1.union(set2)
print("Union of Set 1 and Set 2:", union_set)

# Intersection of sets (common elements in both sets)
intersection_set = set1.intersection(set2)
print("Intersection of Set 1 and Set 2:", intersection_set)

# Difference between sets (elements in Set 1 but not in Set 2)
difference_set1 = set1.difference(set2)
print("Set 1 - Set 2 (Difference):", difference_set1)

# Symmetric difference (elements in either set, but not in both)
symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric Difference of Set 1 and Set 2:", symmetric_difference_set)

# Subset and Superset checks
subset_check = {3, 4}.issubset(set1)
print("{3, 4} is a subset of Set 1:", subset_check)

superset_check = set1.issuperset({3, 4})
print("Set 1 is a superset of {3, 4}:", superset_check)