# -*- coding: utf-8 -*-
"""task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176hyBOuXyTSL0CQilNejYByD55ZW4jjF
"""

print("hello world")













